---
- name: install repmgr10
  yum: 
    name: "{{ item }}" 
    state: present
  with_items:
  - repmgr10
  #- postgresql-10-repmgr

- name: create postgresql conf dir
  file:
    path: "{{ repmgr_postgresql_conf_dir }}"
    state: directory
    recurse: yes
- name: update postgres settings
  template:
    src: postgresql.conf.j2
    dest: "{{ repmgr_postgresql_conf_dir }}/{{ repmgr_postgresql_conf_file }}"
  register: postgresql_conf

- name: create repmgr conf dir
  file:
    path: "{{ repmgr_conf_dir }}"
    state: directory
    recurse: yes
- name: create repmgr conf
  template:
    src: repmgr.conf.j2
    dest: "{{ repmgr_conf_dir }}/{{ repmgr_conf_file }}"
  register: repmgr_conf

- name: restart postgres-10
  service: name={{ repmgr_postgresql_service_name }} state=restarted
  when: postgresql_conf.changed

- name: register with repmgr
  shell: "/usr/pgsql-10/bin/repmgr -f {{ repmgr_conf_dir }}/{{ repmgr_conf_file }} --verbose master register --force"
  become: true
  become_user: postgres
  become_method: sudo
  when: repmgr_conf.changed and repmgr_is_master|bool

- include_tasks: standby-post-tasks.yml
  when:
  - "postgresql_repmgr_standby in group_names"
